[sampling]
nreplicas = 8
nprocs_per_replica = 1
kTstart = 0.9
kTend = 1.3
nsteps = 8192 # Number of steps for sampling
RXtrial_frequency = 64
sample_frequency = 8
print_frequency = 1
reload = false

[sampling.solver]
type = 'potts'
Q = 2
L = [16,16]
